repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive

      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide requirements
        files: ^ecs/

  - repo: local
    hooks:
      - id: spacelift-local-preview
        name: Spacelift Local Preview
        entry: bash -c 'cd ecs && spacelift stack local-preview --id ecs'
        language: system
        pass_filenames: false
        files: ^ecs/.*\.tf$
